version: "3.5"

services:
  node-web-server:
    platform: linux/amd64
    container_name: node-web-server
    restart: always
    build:
      context: ./thumbs-server
      dockerfile: Dockerfile
    image: thumbs-server:v1.1
    env_file:
      - ./thumbs-server/.env
    ports:
      - 8000:8000
    networks:
      - thumbs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
networks:
  thumbs:
