version: "3.5"

services:
    server:
        build:
            context: ./thumbs-server
            dockerfile: Dockerfile
        image: thumbs-server:v1.0
        env_file:
            - ./thumbs-server/.env
        ports:
            - 3001:3001
        networks:
            - thumbs
    web:
        depends_on:
            - server
        build:
            context: ./thumbs-web
            dockerfile: Dockerfile
        image: thumbs-web:v1.0
        env_file:
            - ./thumbs-web/.env
        ports:
            - 3000:3000
        networks:
            - thumbs
networks:
    thumbs:
