version: "3.5"

services:
  node-web-server:
    container_name: node-web-server
    build:
      context: ./thumbs-server
      dockerfile: Dockerfile
    image: thumbs-server:v1.0
    env_file:
      - ./thumbs-server/.env
    ports:
      - 8000:8000
    networks:
      - thumbs
networks:
  thumbs:
